### ISSUE TITLE
Create new script to stream quotes to csv

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/tasty-quant#5]
## **1. Project Structure**

First, let's outline the updated project structure:

```
your_project/
├── tasty-quote-streamer.py
├── tasty-quote-streamer.yaml
├── data/
│   ├── positions-watchlist.csv
│   └── (output CSV files will be generated here)
├── tasty-quote-streamer.log
└── requirements.txt
```

- **`tasty-quote-streamer.py`**: The main Python script.
- **`tasty-quote-streamer.yaml`**: Configuration file containing all configurable parameters.
- **`data/`**: Directory to store the watchlist and output CSV files.
- **`tasty-quote-streamer.log`**: Log file generated by the script.
- **`requirements.txt`**: Python dependencies.

---

## **2. Configuration File**

We'll use a **YAML** configuration file (`tasty-quote-streamer.yaml`) to store all configurable parameters. YAML is human-readable and widely used for configuration purposes in Python projects.

### **`tasty-quote-streamer.yaml`**

```yaml
# tasty-quote-streamer.yaml

logging:
  level: INFO
  file: tasty-quote-streamer.log

portfolio:
  file: data/positions-watchlist.csv

output:
  directory: data/
  strategy_filename_template: "strategy-mtm-{date}.csv"
  positions_filename_template: "positions-quotes-{date}.csv"

streaming:
  symbols: # Optional: Specify symbols here to override the portfolio CSV
    # - ".AAPL250117C250"
    # - ".AAPL250117C245"
```

### **Explanation:**

- **`logging`**:
  - **`level`**: Sets the logging level (e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL).
  - **`file`**: Specifies the log file name.

- **`portfolio`**:
  - **`file`**: Path to the portfolio CSV file (`positions-watchlist.csv`).

- **`output`**:
  - **`directory`**: Directory where output CSV files will be stored.
  - **`strategy_filename_template`**: Template for the strategy CSV filename, with `{date}` as a placeholder for the current date in `YYYYMMDD` format.
  - **`positions_filename_template`**: Template for the positions quotes CSV filename, with `{date}` as a placeholder for the current date.

- **`streaming`**:
  - **`symbols`**: Optional list of symbols to subscribe to. If empty, the script will load symbols from the portfolio CSV.

---

## **3. `requirements.txt`**

To handle YAML configurations, we'll use the `PyYAML` library. Additionally, ensure all other dependencies are listed.

### **`requirements.txt`**

```
pandas
tastytrade
PyYAML
```

**Installation:**

Before running the script, install the dependencies using `pip`:

```bash
pip install -r requirements.txt
```

## **4. **Enhanced Data Handling:**

   - **`quotes_data` Dictionary:**
     - Stores the latest `Quote` objects keyed by `event_symbol`.
     - This provides access to bid and ask details needed for the positions quotes CSV.

   - **Data Merging:**
     - Merges the latest quotes with the portfolio DataFrame to prepare data for CSV output.

5. **Graceful Shutdown:**

   - **Signal Handling:**
     - Catches `SIGINT` and `SIGTERM` signals to initiate a graceful shutdown.
     - Cancels running tasks and ensures all resources are properly released.

6. **Error Handling:**

   - **Try-Except Blocks:**
     - Comprehensive error handling throughout the script to manage unexpected scenarios without crashing.
     - Logs errors with stack traces for easier debugging.

7. **Performance Optimization:**

   - **Vectorized Operations:**
     - Utilizes Pandas' vectorized operations for efficient data processing.

   - **Efficient Data Writing:**
     - Writes data to CSV files in batches during periodic updates instead of per quote, reducing I/O overhead.

---
